// transactins json data
export const Data = [
  {
    id: "1",
    type: "out",
    amount: "600",
    currency: "Kesh",
    date: "202320-01-01",
    description: "description",
    status: "error",
  },
  {
    id: "2",
    type: "out",
    amount: "200",
    currency: "USD",
    date: "2020-01-01",
    description: "description",
    status: "success",
  },
  {
    id: "2",
    type: "out",
    amount: "200",
    currency: "USD",
    date: "2020-01-01",
    description: "description",
    status: "error",
  },
  {
    id: "3",
    type: "in",
    amount: "300",

    currency: "USD",
    date: "2020-01-01",
    description: "description",
    status: "success",
  },
  {
    id: "4",
    type: "out",
    amount: "400",
    currency: "USD",
    date: "2020-01-01",
    description: "description",
    status: "success",
  },
  {
    id: "5",
    type: "in",
    amount: "500",
    currency: "USD",
    date: "2020-01-01",

    description: "description",
    status: "pending",
  },

  {
    id: "6",
    type: "out",

    amount: "600",
    currency: "USD",
    date: "2020-01-01",
    description: "description",
    status: "success",
  },
  {
    id: "7",
    type: "in",
    amount: "700",
    currency: "USD",
    date: "2020-01-01",
    description: "description",
    status: "error",
  },
  {
    id: "8",
    type: "out",
    amount: "800",
    currency: "USD",
    date: "2020-01-01",
    description: "description",
    status: "success",
  },
  {
    id: "9",
    type: "in",
    amount: "900",
    currency: "USD",
    date: "2020-01-01",
    description: "description",
    status: "success",
  },
  {
    id: "10",
    type: "out",
    amount: "1000",
    currency: "USD",
    date: "2020-01-01",
    description: "description",
    status: "success",
  },
  {
    id: "11",
    type: "in",
    amount: "1100",
    currency: "USD",
    date: "2020-01-01",
    description: "description",
    status: "success",
  },
];
